#!/usr/bin/env php
<?php

if (version_compare(PHP_VERSION, '8.1') === -1) {
  throw new Exception('You need at least PHP 8.1 in order for CRON to work.');
}

require __DIR__.'/bootstrap/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);
$kernel->terminate($input, $status);
exit($status);
